### PR TITLE
Add support for text-based block/item IDs

### PR DESCRIPTION
**Pull request by Gargaj**
Should work for the most part, I tried to add all the itemIDs that didn't match the naming convention - didn't add any of the 1.8.x blocks though. The Get* functions could be changed into a string-based cached dictionary.

### CODE REVIEW

**Comment by Gargaj** [comment]
https://github.com/minecraft-dotnet/Substrate/pull/33 is a much better solution

**Comment by redwyre** [comment]
Were your NBT changes based on real world data or pre-emptive? I haven't seen the name ids used yet.

**Comment by Gargaj** [comment]
They're definitely used in 1.8+ worlds.

**Comment by redwyre** [comment]
Can you provide some links and/or data? And feel free to re-submit your nbt changes against the 2.x branch

**Comment by Gargaj** [comment]
Which bits are you referring to? Whatever I did I think you did better.

**Pull request closed without merging**
